export const ActionTypes = {
	SET_PRODUCTS : "SET_PRODUCTS",
	SELECTED_PRODUCTS : "SELECTED_PRODUCT",

	// Actions for Pokemon Management
	ADD_TRAINER : "ADD_TRAINER",
	ADD_POKEMON : "ADD_POKEMON",
	DELETE_TRAINER: "DELETE_TRAINER",
	DELETE_POKEMON: "DELETE_POKEMON",
	SEARCH_POKEMON: "SEARCH_TRAINER",

	SET_PROJECTS: "SET_PROJECTS"
	
};